fix bg shutdown test
e-orz/CM-Well pull request #8
Opened 2019-01-27 14:25 UTC by lielShraga

2019-01-28 07:23 UTC, e-orz requested changes

2019-01-28 07:23 UTC, e-orz commented on server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
> +      sender ! true
please use a proper case object

2019-01-28 07:23 UTC, e-orz commented on server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
> +case object Kill
dead code

2019-01-28 07:23 UTC, e-orz commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGResilienceSpec.scala
> +  implicit val timeout = Timeout(30.seconds)
instead of implicit timeout that can confuse the user - please pass it explicitly to the required method.

2019-01-28 07:23 UTC, e-orz commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGResilienceSpec.scala
> +    kafkaProducer.close()
don't you need to close also irw?

2019-01-28 07:23 UTC, e-orz commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGSequentialSpec.scala
> +  implicit val timeout = Timeout(30.seconds)
instead of implicit timeout that can confuse the user - please pass it explicitly to the required method.

2019-01-28 07:23 UTC, e-orz commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGSequentialSpec.scala
> +      kafkaProducer.close()
kill irw?

2019-01-28 07:45 UTC, lielShraga commented on server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
> +case object Kill
done

2019-01-28 08:19 UTC, lielShraga commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGResilienceSpec.scala
> +  implicit val timeout = Timeout(30.seconds)
done

2019-01-28 08:32 UTC, lielShraga commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGResilienceSpec.scala
> +    kafkaProducer.close()
no.it contains dao and I shutdown it

2019-01-28 08:35 UTC, lielShraga commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGSequentialSpec.scala
> +  implicit val timeout = Timeout(30.seconds)
done

2019-01-28 08:36 UTC, lielShraga commented on server/cmwell-bg/src/test/scala/cmwell/bg/test/BGSequentialSpec.scala
> +      kafkaProducer.close()
no need

2019-02-03 09:30 UTC, e-orz approved these changes

2019-02-03 09:30 UTC, merged